name: Node CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [20.x]

    steps:
      # Check-out repository under GitHub workspace
      - uses: actions/checkout@v4
        name: Checkout code

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: make install

      # Run linting
      - run: make lint

      # Run tests
      - run: make test

      # Test & publish code coverage to Code Climate
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        with:
          coverageCommand: make test-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
